export interface CommonProps {
  /**
   * class contains the Tailwind or global class names to apply on the outermost element.
   *
   * Important: this is limited to Tailwind or global class names as Astro creates strict style
   *            scopes for separate components os children would not inherit styles from their
   *            parents.
   */
  class?: string
}

export interface CommonPropsReact {
  /**
   * className contains the Tailwind or global class names to apply on the outermost element.
   *
   * Important: this is limited to Tailwind or global class names as Astro creates strict style
   *            scopes for separate components os children would not inherit styles from their
   *            parents.
   */
  className?: string
}

// PickOptional is generated by Google AI Overview:
type PickOptional<T> = Pick<
  T,
  {
    [K in keyof T]-?: {} extends Pick<T, K> ? K : never;
  }[keyof T]
>;

export type Default<T> = Required<Omit<PickOptional<T>, "class">>

export function getProps<T extends CommonProps>(props: T, defaults: Default<T>) : T {
  return { class: "", ...defaults, ...props }
}

// RequireAtLeastOne is generated by Google AI Overview and partially modified:
export type RequireAtLeastOne<T, Keys> =
  Keys extends keyof T
    ? Required<Pick<T, Keys>> & Partial<Omit<T, Keys>>
    : never;
